{{- $needsSecret := false -}}
{{- if and .Values.storage.influxdb.enabled .Values.storage.influxdb.token (not .Values.storage.influxdb.existingSecret) -}}
  {{- $needsSecret = true -}}
{{- end -}}
{{- if and .Values.storage.splunkHec.enabled .Values.storage.splunkHec.token (not .Values.storage.splunkHec.existingSecret) -}}
  {{- $needsSecret = true -}}
{{- end -}}
{{- if and .Values.storage.pagerduty.enabled .Values.storage.pagerduty.routingKey (not .Values.storage.pagerduty.existingSecret) -}}
  {{- $needsSecret = true -}}
{{- end -}}
{{- if $needsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crabby.fullname" . }}
  labels:
    {{- include "crabby.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.storage.influxdb.enabled .Values.storage.influxdb.token (not .Values.storage.influxdb.existingSecret) }}
  influxdb-token: {{ .Values.storage.influxdb.token | quote }}
  {{- end }}
  {{- if and .Values.storage.splunkHec.enabled .Values.storage.splunkHec.token (not .Values.storage.splunkHec.existingSecret) }}
  splunk-hec-token: {{ .Values.storage.splunkHec.token | quote }}
  {{- end }}
  {{- if and .Values.storage.pagerduty.enabled .Values.storage.pagerduty.routingKey (not .Values.storage.pagerduty.existingSecret) }}
  pagerduty-routing-key: {{ .Values.storage.pagerduty.routingKey | quote }}
  {{- end }}
{{- end }}
